<?php
/**
 * implements hook_menu()
 */
function employee_menu(){
	return array(
	    'admin/content/employee' => array(
	      'title' => 'List Employees',
	      'route_name' => 'employee.list',
	    ),
	    'admin/content/employee/add' => array(
	      'title' => 'Add an employee',
	      'route_name' => 'employee.add',
	    ),
	    'admin/content/employee/{employee}/edit' => array(
	      'title' => 'Edit Employee',
	      'route_name' => 'employee.edit',
	    ),
	    'admin/content/employee/{employee}' => array(
	      'title' => 'View Employee',
	      'route_name' => 'employee.view',
	    ),
	    'admin/content/employee/{id}/delete' => array(
	      'title' => 'Delete an employee',
	      'route_name' => 'employee.delete',
	    ),
    );
}

/**
 * implements hook_mail()
 */
function employee_mail($key, &$message, $params) {
 switch ($key) {
   case 'send_employee_mail':
     $message['from'] = \Drupal::config('system.site')->get('mail');
     $message['subject'] = $params['subject'];
     $message['body'][] = $params['message'];
     break;
	 case 'send_welcome_mail':
     $message['from'] = \Drupal::config('system.site')->get('mail');
		 $employee = $params['employee'];
     $message['subject'] = 'Welcome Abroad '.$employee->name;
		 $message_body = "Dear ".$employee->name." \n";
		 $message_body.= "Welcome to our organisation.
		 	Your Employee Id is: ".$employee->id." \n\n";
		 $message_body.= "Regards, \n TechAspect family";
     $message['body'][] = $message_body;
     break;
 }
}

/**
 * implements hook_views_data()
 */
function employee_views_data(){
	$data = array();
	$data['employee']['table']['group']  = t('Employee');
	$data['employee']['table']['provider'] = 'employee';
	$data['employee']['table']['base'] = array(
  	'field' => 'id', // This is the identifier field for the view.
  	'title' => t('Employee'),
  	'help' => t('Table containing employee records'),
  	'weight' => -10,
	);

	$data['employee']['id'] = array(
	    'title' => t('Employee Id'),
	    'help' => t('Employee Id'),
	    'field' => array(
	      // ID of field handler plugin to use.
	      'id' => 'numeric',
	    ),
	    'sort' => array(
	      // ID of sort handler plugin to use.
	      'id' => 'standard',
	    ),
	    'filter' => array(
	      // ID of filter handler plugin to use.
	      'id' => 'numeric',
	    ),
	    'argument' => array(
	      // ID of argument handler plugin to use.
	      'id' => 'numeric',
	    ),
	);
	$data['employee']['name'] = array(
	    'title' => t('Employee Name'),
	    'field' => array(
	      'id' => 'standard',
	    ),
	    'sort' => array(
	      'id' => 'standard',
	    ),
	    'filter' => array(
	      'id' => 'string',
	    ),
	    'argument' => array(
	      'id' => 'string',
	    ),
	);
	$data['employee']['email'] = array(
	    'title' => t('Employee Email'),
	    'field' => array(
	      'id' => 'standard',
	    ),
	    'sort' => array(
	      'id' => 'standard',
	    ),
	    'filter' => array(
	      'id' => 'string',
	    ),
	    'argument' => array(
	      'id' => 'string',
	    ),
	);
	$data['employee']['department'] = array(
	    'title' => t('Department'),
	    'field' => array(
	      'id' => 'standard',
	    ),
	    'sort' => array(
	      'id' => 'standard',
	    ),
	    'filter' => array(
	      'id' => 'in_operator',
	      'options callback' => '_employee_get_department_lists',
	    ),
	    'argument' => array(
	      'id' => 'string',
	    )
	);
	$data['employee']['address'] = array(
	    'title' => t('Address'),
	    'field' => array(
	      'id' => 'standard',
	    ),
	    'sort' => array(
	      'id' => 'standard',
	    ),
	    'filter' => array(
	      'id' => 'string',
	    ),
	    'argument' => array(
	      'id' => 'string',
	    ),
	);
	$data['employee']['country'] = array(
	    'title' => t('Country'),
	    'field' => array(
	      'id' => 'standard',
	    ),
	    'sort' => array(
	      'id' => 'standard',
	    ),
	    'filter' => array(
	      'id' => 'string',
	    ),
	    'argument' => array(
	      'id' => 'string',
	    ),
	);
	$data['employee']['state'] = array(
	    'title' => t('State'),
	    'field' => array(
	      'id' => 'standard',
	    ),
	    'sort' => array(
	      'id' => 'standard',
	    ),
	    'filter' => array(
	      'id' => 'string',
	    ),
	    'argument' => array(
	      'id' => 'string',
	    ),
	);
	return $data;
}

/**
 * Provides options for in_operator views filter
 */
function _employee_get_department_lists() {
  return array(
    'Development' => 'Development',
    'HR' => 'HR',
    'Sales' => 'Sales',
    'Marketing' => 'Marketing'
  );
}
