<?php

/**
 * @file
 * Contains employee.module.
 */

/**
 * Implements hook_menu().
 */
function employee_menu() {
  return [
    'admin/content/employee' => [
      'title' => 'List Employees',
      'route_name' => 'employee.list',
    ],
    'admin/content/employee/add' => [
      'title' => 'Add an employee',
      'route_name' => 'employee.add',
    ],
    'admin/content/employee/{employee}/edit' => [
      'title' => 'Edit Employee',
      'route_name' => 'employee.edit',
    ],
    'admin/content/employee/{employee}' => [
      'title' => 'View Employee',
      'route_name' => 'employee.view',
    ],
    'admin/content/employee/{id}/delete' => [
      'title' => 'Delete an employee',
      'route_name' => 'employee.delete',
    ],
  ];
}

/**
 * Implements hook_mail().
 */
function employee_mail($key, &$message, $params) {
  switch ($key) {
    case 'send_employee_mail':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['message'];
      break;

    case 'send_welcome_mail':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $employee = $params['employee'];
      $message['subject'] = 'Welcome Abroad ' . $employee->name;
      $message_body = "Dear " . $employee->name . " \n";
      $message_body .= "Welcome to our organisation.
		 	Your Employee Id is: " . $employee->id . " \n\n";
      $message_body .= "Regards, \n TechAspect family";
      $message['body'][] = $message_body;
      break;
  }
}

/**
 * Implements hook_views_data().
 */
function employee_views_data() {
  $data = [];
  $data['employee']['table']['group'] = t('Employee');
  $data['employee']['table']['provider'] = 'employee';
  $data['employee']['table']['base'] = [
  // This is the identifier field for the view.
    'field' => 'id',
    'title' => t('Employee'),
    'help' => t('Table containing employee records'),
    'weight' => -10,
  ];

  $data['employee']['id'] = [
    'title' => t('Employee Id'),
    'help' => t('Employee Id'),
    'field' => [
          // ID of field handler plugin to use.
      'id' => 'numeric',
    ],
    'sort' => [
          // ID of sort handler plugin to use.
      'id' => 'standard',
    ],
    'filter' => [
          // ID of filter handler plugin to use.
      'id' => 'numeric',
    ],
    'argument' => [
          // ID of argument handler plugin to use.
      'id' => 'numeric',
    ],
  ];
  $data['employee']['name'] = [
    'title' => t('Employee Name'),
    'field' => [
      'id' => 'standard',
    ],
    'sort' => [
      'id' => 'standard',
    ],
    'filter' => [
      'id' => 'string',
    ],
    'argument' => [
      'id' => 'string',
    ],
  ];
  $data['employee']['email'] = [
    'title' => t('Employee Email'),
    'field' => [
      'id' => 'standard',
    ],
    'sort' => [
      'id' => 'standard',
    ],
    'filter' => [
      'id' => 'string',
    ],
    'argument' => [
      'id' => 'string',
    ],
  ];
  $data['employee']['department'] = [
    'title' => t('Department'),
    'field' => [
      'id' => 'standard',
    ],
    'sort' => [
      'id' => 'standard',
    ],
    'filter' => [
      'id' => 'in_operator',
      'options callback' => '_employee_get_department_lists',
    ],
    'argument' => [
      'id' => 'string',
    ],
  ];
  $data['employee']['address'] = [
    'title' => t('Address'),
    'field' => [
      'id' => 'standard',
    ],
    'sort' => [
      'id' => 'standard',
    ],
    'filter' => [
      'id' => 'string',
    ],
    'argument' => [
      'id' => 'string',
    ],
  ];
  $data['employee']['country'] = [
    'title' => t('Country'),
    'field' => [
      'id' => 'standard',
    ],
    'sort' => [
      'id' => 'standard',
    ],
    'filter' => [
      'id' => 'string',
    ],
    'argument' => [
      'id' => 'string',
    ],
  ];
  $data['employee']['state'] = [
    'title' => t('State'),
    'field' => [
      'id' => 'standard',
    ],
    'sort' => [
      'id' => 'standard',
    ],
    'filter' => [
      'id' => 'string',
    ],
    'argument' => [
      'id' => 'string',
    ],
  ];
  return $data;
}

/**
 * Provides options for in_operator views filter.
 */
function _employee_get_department_lists() {
  return [
    'Development' => 'Development',
    'HR' => 'HR',
    'Sales' => 'Sales',
    'Marketing' => 'Marketing',
  ];
}
